services:
  django:
    environment:
      DEBUG: False
    depends_on:
      - postgres
  daphne:
    environment:
      DEBUG: False
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    env_file:
      - .env
    expose:
      - 5432
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data/
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
