
services:
  django:
    env_file:
      - .env
    environment:
      - USE_DOCKER=True
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - develop-net
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
      - ./app:/app
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    depends_on:
      - django
    networks:
      - develop-net
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/static
    restart: always

volumes:
  static_volume:

networks:
  develop-net:
    driver: bridge
